name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: simple_bank
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

jobs:

  test:
    runs-on: ubuntu-latest

     # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        image: postgres:10.23-alpine3.16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install golang migrate
      run: |
        # Get the latest version
        version=$(curl -s https://api.github.com/repos/golang-migrate/migrate/releases/latest | jq -r .tag_name)

        # Get the os and arch
        os=$(uname -s | tr '[:upper:]' '[:lower:]')
        arch=$(uname -m | sed 's/x86_64/amd64/')

        # Download and install migrate
        curl -L https://github.com/golang-migrate/migrate/releases/download/$version/migrate.$os-$arch.tar.gz | tar xvz

        # Move the binary to the bin folder
        sudo mv migrate /usr/local/bin/migrate

        # Make the binary executable
        which migrate

    - name: run migrations
      run: make migrateup
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: simple_bank
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432

    - name: Test
      run: make test
